builders:
  strip_metadata:
    import: "package:tavern/tavern.dart"
    builder_factories:
      - metadataBuilder
    build_extensions:
      .md:
        - .metadata
        - .contents
    auto_apply: root_package
    required_inputs:
      - .md
  markdown:
    import: "package:tavern/tavern.dart"
    builder_factories:
      - markdownBuilder
    build_extensions:
      .contents:
        - .mustache
    auto_apply: root_package
    required_inputs:
      - .contents
  mustache:
    import: "package:tavern/tavern.dart"
    builder_factories:
    - mustacheBuilder
    build_extensions:
      .mustache:
      - .html
    auto_apply: root_package
    required_inputs:
    - .mustache
    - .metadata
    applies_builders:
      - tavern|cleanup
post_process_builders:
  cleanup:
    import: "package:tavern/tavern.dart"
    builder_factory: cleanupBuilder
