builders:
  strip_metadata:
    import: "package:tavern/tavern.dart"
    builder_factories:
      - metadataBuilder
    build_extensions:
      .md:
        - .metadata
        - .mdcontent
    auto_apply: root_package
    required_inputs:
      - .md
  markdown:
    import: "package:tavern/tavern.dart"
    builder_factories:
      - markdownBuilder
    build_extensions:
      .mdcontent:
        - .htmlcontent
    auto_apply: root_package
    required_inputs:
      - .mdcontent
  mustache:
    import: "package:tavern/tavern.dart"
    builder_factories:
    - mustacheBuilder
    build_extensions:
      .htmlcontent:
      - .html
    auto_apply: root_package
    required_inputs:
    - .mustache
    - .metadata
    - .htmlcontent
#    applies_builders:
#      - tavern|cleanup
#post_process_builders:
#  cleanup:
#    import: "package:tavern/tavern.dart"
#    builder_factory: cleanupBuilder
