builders:
  strip_metadata:
    import: "package:tavern/tavern.dart"
    builder_factories:
      - metadataBuilder
    build_extensions:
      .md:
        - .metadata
        - .mdcontent
    auto_apply: root_package
    required_inputs:
      - .md
  markdown:
    import: "package:tavern/tavern.dart"
    builder_factories:
      - markdownBuilder
    build_extensions:
      .mdcontent:
        - .htmlcontent
    auto_apply: root_package
    required_inputs:
      - .mdcontent
  partial:
    import: "package:tavern/tavern.dart"
    builder_factories:
    - partialBuilder
    build_extensions:
      .htmlcontent:
      - .withpartials
    auto_apply: root_package
    required_inputs:
    - .htmlcontent
  mustache:
    import: "package:tavern/tavern.dart"
    builder_factories:
    - mustacheBuilder
    build_extensions:
      .withpartials:
      - .html
    auto_apply: root_package
    required_inputs:
    - .mustache
    - .metadata
    - .withpartials
    applies_builders:
      - tavern|cleanup
post_process_builders:
  cleanup:
    import: "package:tavern/tavern.dart"
    builder_factory: cleanupBuilder
