builders:
  strip_metadata:
    import: "package:tavern/tavern.dart"
    builder_factories:
      - metadataBuilder
    build_extensions:
      .md:
        - .metadata
        - .mdcontent
    auto_apply: root_package
    required_inputs:
      - .md
  partial:
    import: "package:tavern/tavern.dart"
    builder_factories:
    - partialBuilder
    build_extensions:
      .mdcontent:
      - .withpartials
    auto_apply: root_package
    required_inputs:
    - .mdcontent
  markdown:
    import: "package:tavern/tavern.dart"
    builder_factories:
      - markdownBuilder
    build_extensions:
      .withpartials:
        - .htmlcontent
    auto_apply: root_package
    required_inputs:
      - .withpartials
  mustache:
    import: "package:tavern/tavern.dart"
    builder_factories:
    - mustacheBuilder
    build_extensions:
      .htmlcontent:
      - .html
    auto_apply: root_package
    required_inputs:
    - .htmlcontent
#    applies_builders:
#      - tavern|cleanup
post_process_builders:
  cleanup:
    import: "package:tavern/tavern.dart"
    builder_factory: cleanupBuilder
