builders:
  strip_metadata:
    import: "package:tavern/tavern.dart"
    builder_factories:
      - metadataBuilder
    build_extensions:
      .md:
        - .metadata
        - .contents
    auto_apply: root_package
    required_inputs:
      - .md
  markdown:
    import: "package:tavern/tavern.dart"
    builder_factories:
      - markdownBuilder
    build_extensions:
      .contents:
        - .html_template
    auto_apply: root_package
    required_inputs:
      - .contents
  template:
    import: "package:tavern/tavern.dart"
    builder_factories:
    - templateBuilder
    build_extensions:
      .html_template:
      - .html
    auto_apply: root_package
    required_inputs:
    - .html_template
    - .metadata
