name: tavern
description: A static site generator in Dart
version: 3.0.0
homepage: https://github.com/johnpryan/tavern
author: John Ryan <john.p.ryan4@gmail.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  build: ^1.0.0
  markdown: ^2.0.0
  yaml: ^2.1.0
  mustache: any

dev_dependencies:
  test: ^1.0.0
  pedantic: ^1.0.0
